### ISSUE TITLE
突然不work了？

### ISSUE THREAD

**Issue by RUITAO-WU** [cdpath/anki_tools#3]
你好，
今天突然发现这个popclip to anki的插件不work了。
我就开了popclip to anki这一个anki插件。已经用了一个月左右，昨天还有效的，不知原因为何，能帮忙看看吗？
万分感谢！

附上错误的信息：

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-03 11:57:31
Add-ons possibly involved: ⁨AnkiConnect⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/__init__.py", line 88, in advance
    self.server.advance()
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 128, in advance
    self.advanceClients()
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 143, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 143, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 66, in advance
    self.writeBuff += self.handler(req)
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 199, in handlerWrapper
    if params.get('action', '') == 'requestPermission':
UnboundLocalError: local variable 'params' referenced before assignment

**Comment by cdpath** [comment]
Hi, 升级 AnkiConnect⁩ 试试？

**Comment by RUITAO-WU** [comment]
解决了！
无法升级，之前也试过disable之后重开，都没有解决。
卸载了ankiconnect然后重新安装，再重新启动anki，问题解决了。
感谢！
