### ISSUE TITLE
突然不工作了

### ISSUE THREAD

**Issue by RUITAO-WU** [cdpath/anki_tools#4]
你好，
非常感谢您开发的这个工具，对我的学习生活非常有益。
今天突然发现这个工具又不work了。看起来是anki-connect的问题，但是尝试着重新安装anki-connect没有起作用，能帮忙检查一下吗？
非常感谢！

附：错误信息：
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-30 16:01:21
Add-ons possibly involved: ⁨AnkiConnect⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/__init__.py", line 96, in advance
    self.server.advance()
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 135, in advance
    self.advanceClients()
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 150, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 150, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 67, in advance
    self.writeBuff += self.handler(req)
  File "/Users/ruitaowu/Library/Application Support/Anki2/addons21/2055492159/web.py", line 190, in handlerWrapper
    if params.get('action', '') == 'requestPermission':
UnboundLocalError: local variable 'params' referenced before assignment

**Comment by cdpath** [comment]
是 PopClip 还是 Alfred？

**Comment by RUITAO-WU** [comment]
> 是 PopClip 还是 Alfred？

你好，这个是PopClip的问题

**Comment by cdpath** [comment]
看上去是 AnkiConnect 的问题.
Anki Version ⁨2.1.54 (b6a7760c)⁩ / AnkiConnect 2022-07-15 测试没问题.

**Comment by RUITAO-WU** [comment]
经过测试，现在已经能工作了！感谢！
